# Generated by Django 4.1.3 on 2022-11-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_building', models.CharField(max_length=150)),
                ('name_company', models.CharField(max_length=150)),
                ('quarters', models.IntegerField()),
            ],
        ),
    ]
